main: me.zombie_striker.wcsr.Main
version: 1.0.13
api-version: 1.13
name: WorldChangeScreenRemover
softdepend: [ProtocolLib, PlaceHolderAPI, Multiverse-Core]
author:
   Zombie_Striker
commands:
  wcsr:
    description: Controls the reload command