main: me.zombie_striker.wcsr.Main
version: 1.0.5
name: WorldChangeScreenRemover
softdepend: [ProtocolLib, PlaceHolderAPI, Multiverse-Core]
author:
   Zombie_Striker
commands:
  wcsr:
    description: Controls the reload command